name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v5

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Generate a changelog
        run: pnpm exec releaseasy changelog -vv -o --latest

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          prerelease: ${{ contains(github.ref_name, '-') }}
